### ISSUE TITLE
About Cuda  deserialize object

### ISSUE THREAD

**Issue by schrodingercatss** [zeruniverse/neural-colorization#11]
There is a video card in my computer, but when I use the following command, I am prompted that it cannot be mapped。
`python colorize.py -m G.pth -i input.jpg -o output.jpg --gpu -1`

`python colorize.py -m G.pth -i input.jpg -o output.jpg --gpu 0`

Error information:
>RuntimeError: Attempting to deserialize object on CUDA device 1 but torch.cuda.device_count() is 1. Please use torch.load with map_location to map
your storages to an existing device.

**Comment by zeruniverse** [comment]
You don’t have CUDA device 1 when count is 1. You only have device 0

**Comment by schrodingercatss** [comment]
Thank you so much. It's settled
