### ISSUE TITLE
Why I meet the loss is 0?

### ISSUE THREAD

**Issue by lkp520** [zeruniverse/neural-colorization#13]
Epoch: 3: [D loss: 50.000000] [G total loss: 16.745750] [G GAN Loss: 0.000000]
Epoch: 3: [D loss: 50.000000] [G total loss: 17.254082] [G GAN Loss: 0.000000]
Epoch: 3: [D loss: 50.000000] [G total loss: 16.371378] [G GAN Loss: 0.000000]
Epoch: 3: [D loss: 50.000000] [G total loss: 14.244134] [G GAN Loss: 0.000000]
Epoch: 3: [D loss: 50.000000] [G total loss: 17.944151] [G GAN Loss: 0.000000]
Epoch: 3: [D loss: 50.000000] [G total loss: 20.372141] [G GAN Loss: 0.000000]
Epoch: 3: [D loss: 50.000000] [G total loss: 17.622280] [G GAN Loss: 0.000000]
Epoch: 3: [D loss: 50.000000] [G total loss: 14.337464] [G GAN Loss: 0.000000]
How can I solve it? Thank you very much!

**Comment by zeruniverse** [comment]
It’s clear something is wrong… I wrote this project long time ago and maybe
pytorch has gone through some changes since then
