### ISSUE TITLE
Porting this network to deeplearn.js (or TensorFlow.js)

### ISSUE THREAD

**Issue by GlebSBrykin** [zeruniverse/neural-colorization#2]
Hello! I really liked Your project, but I have no experience with Torch, Python or Linux at all. Can you help me and convert your project to DeepLearn.JS or TensorFlow.JS (these libraries were developed by Google and can be found on GitHub. They are completely written in JavaScript.). In fact, I am interested in the weight of your neural network. I work in the Windows operating system and study neural networks in C#.

**Comment by zeruniverse** [comment]
Hi,

Thank you for your interest. However, I’ve never written deep learning in
JS. If you are only interested in the model, you can download the
pretrained model and load it using Torch or Pytorch (should be one line
thing). After that, you can export the weights to txt file.

**Comment by GlebSBrykin** [comment]
Thank you for your reply! But I, unfortunately, do not quite understand how to do it. I've never studied Python, Torch, or Linux, so I can't even imagine how it's all done. Is it possible to save the net weights of the model in a binary file (a set of numbers, such as float/single)? I downloaded the pre-learned model, but its structure, as I understand it, is very complex. I only know 2 programming languages: PascalABC.NET and C#.

**Comment by zeruniverse** [comment]
Pytorch can be installed in Windows. http://pytorch.org

And please google ‘how to load model in Pytorch’ you can get very detailed
results.

**Comment by GlebSBrykin** [comment]
Thank you very much! I will explore!
