### ISSUE TITLE
Getting the weights of a given neural network

### ISSUE THREAD

**Issue by GlebSBrykin** [zeruniverse/neural-colorization#3]
Hello! I would love to run Your project, but I can not do it. Could you extract the weights of this neural network and save them to a binary file(as a sequence of numbers like Single) so that I can run the network?

**Comment by zeruniverse** [comment]
Hi,

I currently don’t have torch installed. I think it’s easier that you
install torch yourself and extract the weights.

Get torch here:  http://torch.ch

**Comment by GlebSBrykin** [comment]
I have already contacted you, and since then I have tried to install torch more than once. All attempts were unsuccessful (I work in Windows, Python and all other machine learning frameworks have very little support for this operating system). I have no experience with this language - I only know Pascal and C#. I can only hope for the help of a professional.

**Comment by GlebSBrykin** [comment]
Your project has no analogues. None of those to whom I addressed(including developers of Torch) didn't begin to help.

**Comment by zeruniverse** [comment]
If you just have weights, how will you build the network? Do you know how
to define my model  architecture in your programming language? If so, I can
extract the weights for you (perhaps give you a json file) later.

**Comment by GlebSBrykin** [comment]
You've indicated that Justin Johnson's network architecture is used. I was able to look at the sample network architecture through OpenCV, and it is fully consistent with the one used in my application for styling. You can see my implementation: https://github.com/PABCSoft/ImageStyler. And here is the implementation, thanks to which it became possible: https://github.com/reiinakano/fast-style-transfer-deeplearnjs. Separately I would like to note the format in which the weights were stored. Here is a folder with files for a particular style (i.e., model): https://github.com/reiinakano/fast-style-transfer-deeplearnjs/tree/master/src/ckpts/la_muse. There are a lot of files without extensions, these files in binary format store the weight of individual elements of the network(convolution filters - a separate file, shift for instanceNorm - a separate file, Scale - a separate file, etc.). Next is a JSON file with the size of the arrays stored in these files. Thanks in advance!

**Comment by zeruniverse** [comment]
Sorry I will not have time to read your implementation and your format. The
best I can do is to give you a plain text format file of all weights (so
you can visually read them and process with whatever you like) and the
model specification. You’ll need to take care of the rest.

**Comment by GlebSBrykin** [comment]
I will be overly grateful to that!

**Comment by zeruniverse** [comment]
As promised, model weights in JSON file (open in txt and take a look, weights should be in order):
[weights.zip](https://github.com/zeruniverse/neural-colorization/files/2157697/weights.zip)

Model architecture (Johnson's network with 1 channel input and 2 channel output. Last layer changed to Tanh):
```python
nn.Sequential( # Sequential,
    nn.ReflectionPad2d((40, 40, 40, 40)),
    nn.Conv2d(1,32,(9, 9),(1, 1),(4, 4)),
    nn.BatchNorm2d(32),
    nn.ReLU(),
    nn.Conv2d(32,64,(3, 3),(2, 2),(1, 1)),
    nn.BatchNorm2d(64),
    nn.ReLU(),
    nn.Conv2d(64,128,(3, 3),(2, 2),(1, 1)),
    nn.BatchNorm2d(128),
    nn.ReLU(),
    nn.Sequential( # Sequential,
        LambdaMap(lambda x: x, # ConcatTable,
            nn.Sequential( # Sequential,
                nn.Conv2d(128,128,(3, 3)),
                nn.BatchNorm2d(128),
                nn.ReLU(),
                nn.Conv2d(128,128,(3, 3)),
                nn.BatchNorm2d(128),
            ),
            ShaveImage() # layer information https://github.com/zeruniverse/neural-colorization/blob/master/ShaveImage.lua
        ),
        LambdaReduce(lambda x,y: x+y), # CAddTable,
    ),
    nn.Sequential( # Sequential,
        LambdaMap(lambda x: x, # ConcatTable,
            nn.Sequential( # Sequential,
                nn.Conv2d(128,128,(3, 3)),
                nn.BatchNorm2d(128),
                nn.ReLU(),
                nn.Conv2d(128,128,(3, 3)),
                nn.BatchNorm2d(128),
            ),
            ShaveImage() # layer information https://github.com/zeruniverse/neural-colorization/blob/master/ShaveImage.lua
        ),
        LambdaReduce(lambda x,y: x+y), # CAddTable,
    ),
    nn.Sequential( # Sequential,
        LambdaMap(lambda x: x, # ConcatTable,
            nn.Sequential( # Sequential,
                nn.Conv2d(128,128,(3, 3)),
                nn.BatchNorm2d(128),
                nn.ReLU(),
                nn.Conv2d(128,128,(3, 3)),
                nn.BatchNorm2d(128),
            ),
            ShaveImage() # layer information https://github.com/zeruniverse/neural-colorization/blob/master/ShaveImage.lua
        ),
        LambdaReduce(lambda x,y: x+y), # CAddTable,
    ),
    nn.Sequential( # Sequential,
        LambdaMap(lambda x: x, # ConcatTable,
            nn.Sequential( # Sequential,
                nn.Conv2d(128,128,(3, 3)),
                nn.BatchNorm2d(128),
                nn.ReLU(),
                nn.Conv2d(128,128,(3, 3)),
                nn.BatchNorm2d(128),
            ),
            ShaveImage() # layer information https://github.com/zeruniverse/neural-colorization/blob/master/ShaveImage.lua
        ),
        LambdaReduce(lambda x,y: x+y), # CAddTable,
    ),
    nn.Sequential( # Sequential,
        LambdaMap(lambda x: x, # ConcatTable,
            nn.Sequential( # Sequential,
                nn.Conv2d(128,128,(3, 3)),
                nn.BatchNorm2d(128),
                nn.ReLU(),
                nn.Conv2d(128,128,(3, 3)),
                nn.BatchNorm2d(128),
            ),
            ShaveImage() # layer information https://github.com/zeruniverse/neural-colorization/blob/master/ShaveImage.lua
        ),
        LambdaReduce(lambda x,y: x+y), # CAddTable,
    ),
    nn.ConvTranspose2d(128,64,(3, 3),(2, 2),(1, 1),(1, 1)),
    nn.BatchNorm2d(64),
    nn.ReLU(),
    nn.ConvTranspose2d(64,32,(3, 3),(2, 2),(1, 1),(1, 1)),
    nn.BatchNorm2d(32),
    nn.ReLU(),
    nn.Conv2d(32,2,(9, 9),(1, 1),(4, 4)),
    nn.Tanh(),
)
```

Please note the image should be processed in YUV format rather than RGB. The input will be Y channel (`1*W*H`) minus 0.5 (for centerization) and the output[0]*0.436 is predicted U value and output[1]*0.615 is predicted V value (thus output size is `2*W*H`). With the given Y, you can convert the prediction to RGB.

Try if you can make it work in your framework. If not, please consider installing Linux and installing [torch](http://torch.ch/). Then you can follow the README of this project and run the code. I'm sorry that I won't be able to further help you (converting my project to tensorflow is already out of the project's scope, hope you can understand).

**Comment by zeruniverse** [comment]
Btw, I didn't see anyone who seriously working on deep learning uses Windows. I suggest you using Ubuntu. Ubuntu should be very easy to install. Much much much easier than converting the project to tensorflow. And you get more help from other people if you use Ubuntu...

**Comment by GlebSBrykin** [comment]
Thank you! My goal is not just to learn machine learning, but to prepare good implementations of professionals for use by simple users. Most home PCs run Windows, so I'm developing for this OS.

**Comment by GlebSBrykin** [comment]
I just didn't quite understand what ShaveBlock was doing.

**Comment by zeruniverse** [comment]
Please take a look at the code. I commented the code in last reply

**Comment by PABCSoft** [comment]
I looked, now it is clear. Can you tell us a little more about the format in which the weights are stored, about the sizes of arrays?

**Comment by PABCSoft** [comment]
Is there no error in converting? When executed on an element (d, h, w)=(0, 6, 1) 25 the first layer neuron appears to be in error.

**Comment by PABCSoft** [comment]
Can You keep the weight into a text file Prime numbers separated by spaces or the Enter key, and just write next to the sizes of the arrays? For Example:
2.44535
334.24345
...

**Comment by GlebSBrykin** [comment]
I still have a few questions: what is running_mean and running_var? Where to add bias to ConvTranspose2D and can I do without ShaveBlock in direct distribution?

**Comment by zeruniverse** [comment]
It's for batchnorm params

I don't know (it depends on the framework you use). If there's a weight for convtranspose2d in the weights.json, you should add it to your implementation

You can't get rid of the shaveblock unless you retrain and are ok with worse accuracy.

**Comment by GlebSBrykin** [comment]
> It's for batchnorm params

How exactly do I use them?

> I don't know (it depends on the framework you use)

I don't use frameworks; I write all the layers of the network on my own at the level of simple mathematical operations, such as addition, subtraction, and so on.

> You can't get rid of the shaveblock unless you retrain and are ok with worse accuracy.

Can you just explain in words what he has to do. The code I looked and did not understand.
Started trying to get the network up and running. So far it turns out this:
![10](https://user-images.githubusercontent.com/36363358/42240998-c8b90738-7f11-11e8-8e0a-956bfa9f710b.jpg)
![11](https://user-images.githubusercontent.com/36363358/42241007-cea273b4-7f11-11e8-8a6e-fbbcee4f1c42.jpg)

**Comment by zeruniverse** [comment]
Hi,

Looks like you didn’t turn it into RGB. The output is UV.

I forgot what Shaveblock did since it’s an old project (but I know it did
something, you should read the code or go to Johnson’s project and ask,
it’s a layer from his implementation) And for batch norm, you should
implement it. Search for a paper “batch normalization.”

I really think you should install a Linux and use my torch code to get
started. Or simpler, do virtual machine (virtual box is free) and install
Ubuntu. I will fix the bug of my code but I can’t just help you on
everything.

- Jeffery

**Comment by GlebSBrykin** [comment]
>  I will fix the bug of my code but I can’t just help you on
everything.

I'll try to fix the bug in my code, based on Yours.

> Looks like you didn’t turn it into RGB. The output is UV.

I think so too, but it simply cannot be, the transformation was complete.

Thanks for help!

**Comment by GlebSBrykin** [comment]
![colorized](https://user-images.githubusercontent.com/36363358/42241919-e787d61e-7f14-11e8-8061-5b77b19703b7.jpg)

**Comment by GlebSBrykin** [comment]
Another question is do you use biases in convolutions?

**Comment by zeruniverse** [comment]
I think you would finally need to install torch and run my code to compare
your implementation. Otherwise, you don’t know if your implementation is
right or not

**Comment by zeruniverse** [comment]
If there’s bias in weights I sent to you, then there’s bias on this layer.

**Comment by GlebSBrykin** [comment]
ShaveBlock is, as I understand it, the whole ResidualBlock. But I'm interested in SaveImage (). Here's the code:
```
function layer:updateOutput(input)
  local N, C = input:size(1), input:size(2)
  local H, W = input:size(3), input:size(4)
  local s = self.size
  self.output:resize(N, C, H - 2 * s, W - 2 * s)
  self.output:copy(input[{{}, {}, {s + 1, H - s}, {s + 1, W - s}}])
  return self.output
end
```
What does this code do? I started to study my implementation. Found that the problem with colors is not the network itself, but the color conversion. That is, from YUV to RGB. The Y channel applied to the neural network input is normalized to 1?
![colorized](https://user-images.githubusercontent.com/36363358/42260527-7d174126-7f6d-11e8-91a7-ba181d4eb54d.jpg)

**Comment by GlebSBrykin** [comment]
So, I conducted a few more experiments and got the following results:
![207317_26](https://user-images.githubusercontent.com/36363358/42270163-d6241378-7f88-11e8-9369-271dc97b7bf8.jpg)
Original
![colorized3](https://user-images.githubusercontent.com/36363358/42270202-effecdf6-7f88-11e8-9d82-e1f0bb395692.jpg)
Result
Your network really does! Modernization consisted of the following: biases were removed from each Convolution. I still wanted to know how the Save Image () method works. Perhaps its implementation will improve the quality of the result. I would like to ask you not to close the Issue, as I hope to run a coloring application based on your neural network soon.

**Comment by zeruniverse** [comment]
Congratulations on your progress!

**Comment by GlebSBrykin** [comment]
Implemented a graphical shell for the application. Here are some screenshots.
![1](https://user-images.githubusercontent.com/36363358/42305286-f272fde6-8032-11e8-8450-91ae1a19c882.jpg)
![2](https://user-images.githubusercontent.com/36363358/42305301-05d976ee-8033-11e8-9445-69c77b3302c5.jpg)
![3](https://user-images.githubusercontent.com/36363358/42305320-1f6bbf36-8033-11e8-82c1-ac0460339628.jpg)
![4](https://user-images.githubusercontent.com/36363358/42305326-2b3e53aa-8033-11e8-81b2-13e9d8734d0a.jpg)
![5](https://user-images.githubusercontent.com/36363358/42305341-36f569ea-8033-11e8-9cff-e9ea9be58183.jpg)
![6](https://user-images.githubusercontent.com/36363358/42305349-3ec053f6-8033-11e8-97f6-0abae4716ea3.jpg)
After coloring, the image can be passed through normalization. This improves quality.
![7](https://user-images.githubusercontent.com/36363358/42305375-5cba6784-8033-11e8-865d-b94955807d0d.jpg)
With the help of the program I was able to paint a photo of my city, taken in 1965.
![44769913](https://user-images.githubusercontent.com/36363358/42305463-b5113598-8033-11e8-933f-8fa1bcda60e2.jpg)
![default](https://user-images.githubusercontent.com/36363358/42305477-c47786ae-8033-11e8-8d63-dd5ba8f5a0d9.jpg)
Thank you for your help in implementing the app! Today I will post it on my GitHub page.

**Comment by GlebSBrykin** [comment]
So, the application is ready: https://github.com/PABCSoft/FastNeuralColor!

**Comment by zeruniverse** [comment]
You don’t need to include my id in the app if you didn’t use my code. Idea
is not patented.

**Comment by zeruniverse** [comment]
What’s the current problem? Why so many gray artifacts?

**Comment by zeruniverse** [comment]
Consider writing an English version if possible. I can put link to your
English version on my project’s README.

**Comment by GlebSBrykin** [comment]
> You don’t need to include my id in the app if you didn’t use my code. Idea
is not patented.

I can clean it up if you want. But my design is based on Your. I did not develop the network architecture and did not teach the network.

> What’s the current problem? Why so many gray artifacts?

This was the first version where there was no normalization. I added it:
![2](https://user-images.githubusercontent.com/36363358/42361589-eed55556-80f7-11e8-925e-264b5a9df214.jpg)

> Consider writing an English version if possible. I can put link to your
English version on my project’s README.

Okay, I'll try to do it today.

**Comment by zeruniverse** [comment]
I’m happy if you leave my name in your software. I just mean you don’t
**need to**.

There’s still artifacts...

**Comment by GlebSBrykin** [comment]
Artifacts can be caused by damage to the input image. As you can see, there are a lot of stripes, spots, etc.the photo was Taken in the 60s. If you look at the discolored modern photos, the results are somewhat better.
![default](https://user-images.githubusercontent.com/36363358/42362291-3a9c4e1a-80fb-11e8-8a79-844d5e18b8bd.jpg)

I translated it into English. The source code and binary version are available in the same repository, marked (Eng).

**Comment by zeruniverse** [comment]
Could you post the original images for your test images? I can give you results of my program.

Gray artifacts look really weird

**Comment by GlebSBrykin** [comment]
OK! Original:
![44769913](https://user-images.githubusercontent.com/36363358/42392339-25234786-815b-11e8-908a-c584764cf696.jpg)
Result fron lastest version:
![1d6efc61f2e78ad1e8966e05b33cd6f1f4f02b9a_1_654x500](https://user-images.githubusercontent.com/36363358/42392356-371dac4c-815b-11e8-8d79-792e98fd8fbc.jpg)

**Comment by zeruniverse** [comment]
My bad. Here's my results:

![o](https://user-images.githubusercontent.com/4648756/42401101-f7678a46-8128-11e8-9ae7-25d49f09c80f.png)

![o](https://user-images.githubusercontent.com/4648756/42401117-0ec8829e-8129-11e8-8a7b-747842a43ab7.png)

I think your result is better than mine. There's some problems with torch since it does not support new CUDA and CUDNN and I have to do some workaround. This turns out to harm the performance.

For English, I would like to see a separate branch (make a branch called English and put all English implementations there) with a README written in English. Then I'll link to your English branch in mine.

**Comment by zeruniverse** [comment]
More test data and Torch results:  [test.zip](https://github.com/zeruniverse/neural-colorization/files/2172068/test.zip)

I got the sample image from the README of this project and seems the generated images are incorrect. I'll try to install CUDA 8 and CUDNN v5 to generate original results if I have time. But anyway I think your implementation is OK (give you've implemented conv bias, batch norm and shave layer)

**Comment by zeruniverse** [comment]
I remembered if the network can not predict the color, the area will be simply gray. But I saw your artifacts are yellow. Do you have idea why it happens? This is more significant in your first image (i.e. where you said you don't have batchnorm)

**Comment by GlebSBrykin** [comment]
> For English, I would like to see a separate branch (make a branch called English and put all English implementations there) with a README written in English. Then I'll link to your English branch in mine.

Good. I think I can do it tomorrow night, because now I do not have such an opportunity.

> More test data and Torch results: test.zip

There are very good results!  Tomorrow I will post my results for those images.

> I remembered if the network can not predict the color, the area will be simply gray. But I saw your artifacts are yellow. Do you have idea why it happens?

It is difficult to say, maybe, it is the matter of the formulas of the color transfer from one color space to another. As for the conv and the rest of the data, they are the ones you sent me. I didn't teach my network. The biases I not used, batchnorm is used everywhere, ShaveImage is not used.
I would like to know - do you know Pascal language? Maybe at school or at the Institute?

**Comment by zeruniverse** [comment]
I see the reason. You should use shave block. It’s simply take out the
border of the Conv feature map. But if I have time I might train a new
model using GAN, so there would be no more gray artifacts.

**Comment by zeruniverse** [comment]
I’ll do the shaveblock for you in Pascal tmr

**Comment by GlebSBrykin** [comment]
> I’ll do the shaveblock for you in Pascal tmr

I can do it, just my implementation is written in PascalABC.NET and to understand it you need to know either Pascal or C#. http://pascalabc.net/en/

> I see the reason. You should use shave block. It’s simply take out the
border of the Conv feature map. But if I have time I might train a new
model using GAN, so there would be no more gray artifacts.

I mean, will it be more accurate?

**Comment by zeruniverse** [comment]
On Fri, Jul 6, 2018 at 11:19 PM Глеб Брыкин <notifications@github.com>
wrote:

> I’ll do the shaveblock for you in Pascal tmr
>
> I can do it, just my implementation is written in PascalABC.NET and to
> understand it you need to know either Pascal or C#.
> http://pascalabc.net/en/
>
<http://pascalabc.net/en/>
>
> I see the reason. You should use shave block. It’s simply take out the
> border of the Conv feature map. But if I have time I might train a new
> model using GAN, so there would be no more gray artifacts.
>
> I mean, will it be more accurate?
>

Currently, if objects have multiple possible colours, the network will
become confused and gives gray. Using GAN, the network learns to predict
any color that seems natural, so the gray artifacts will be gone (hopefully)

**Comment by zeruniverse** [comment]
For ShaveImage, it’s very simple. For example, your input feature map is NCWH, the output will be NC(2:W-2)(2:H-2). So in English, you remove the border of 2 pixels at each edge

**Comment by GlebSBrykin** [comment]
Now I understand.

**Comment by GlebSBrykin** [comment]
My results for Your images.
[val.zip](https://github.com/zeruniverse/neural-colorization/files/2173797/val.zip)

**Comment by GlebSBrykin** [comment]
> For English, I would like to see a separate branch (make a branch called English and put all English implementations there) with a README written in English. Then I'll link to your English branch in mine.

How should I create it? I've never done this before.

**Comment by zeruniverse** [comment]
![screenshot from 2018-07-10 09-16-11](https://user-images.githubusercontent.com/4648756/42523212-f2bb725e-8421-11e8-88a3-d571a28e672a.png)

Also look at this: https://guides.github.com/introduction/flow/

```bash
git clone xxx
git checkout English
# do some modification
git commit -a -m 'English'
git push origin English
```

**Comment by GlebSBrykin** [comment]
How do you feel about the implementation of the neural network from Richard Zheng? It is already trained, but implemented on Caffe, which is unusual not only for me, but also for many other programmers, including those who specialize in deep learning. 
Repository with source code and models: https://github.com/richzhang/colorization
Interactive demo version: https://demos.algorithmia.com/colorize-photos/
I think it's quite interesting(the quality of coloring is slightly higher, but the size is more than 20 times).

**Comment by GlebSBrykin** [comment]
> Also

 look at this: https://guides.github.com/introduction/flow/

git clone xxx
git checkout English
# do some modification
git commit -a -m 'English'
git push origin English

Thank you, I'll try now.

**Comment by zeruniverse** [comment]
From what I saw, your implementation is not completely correct. There're a lot of errors around the border. Did you implement the shaveblock?

**Comment by zeruniverse** [comment]
And updates on GAN

![current](https://user-images.githubusercontent.com/4648756/42549383-aef0cc5e-8480-11e8-9667-3ae63c8fbbf8.jpg)

**Comment by GlebSBrykin** [comment]
> From
 what I saw, your implementation is not completely correct. There're a lot of errors around the border. Did you implement the shaveblock?

I implemented it a bit differently: I added the input image with a 40x40 pixel white noise frame, and then, after running through the neural network, cropped that frame. Mistakes along the edges are gone.

![default](https://user-images.githubusercontent.com/36363358/42553185-81bc38e6-84e8-11e8-9aaf-96c204c603c7.jpg)

Is it possible to get the weight of the new model?

**Comment by GlebSBrykin** [comment]
Branch I implemented: https://github.com/PABCSoft/FastNeuralColor/tree/English

**Comment by GlebSBrykin** [comment]
You can check if the new version of my program still has defects at the edges, I will add ShaveBloch from Your technology.

**Comment by zeruniverse** [comment]
I think you already fully understood the shaveblock implementation. Here's Python equivalent anyway:

```python
class shave_block(nn.Module):
    def __init__(self, s):
        super(shave_block, self).__init__()
        self.s=s
    def forward(self,x):
        return x[:,:,self.s:-self.s,self.s:-self.s]
```

`s=2` for all shave blocks.


For weights, I will give it to you soon in a same format.

**Comment by GlebSBrykin** [comment]
> I think you already fully understood the shaveblock implementation.

Yes, I understand. It will be implemented in the near future.

**Comment by GlebSBrykin** [comment]
Will the weights be in JSON?

**Comment by zeruniverse** [comment]
@PABCSoft Please try this: 
[GAN_model.zip](https://github.com/zeruniverse/neural-colorization/files/2196145/GAN_model.zip)

Architecture should be same

**Comment by zeruniverse** [comment]
Any updates on using the new weights?

**Comment by bolimath** [comment]
Hi, Which dataset is used for training the pretrained model "https://github.com/zeruniverse/neural-colorization/releases/download/1.1/G.pth" ?

**Comment by zeruniverse** [comment]
@bolimath  COCO.

Currently trying Places2

**Comment by bolimath** [comment]
@zeruniverse Looks forward to your places2-based model! My test data is COCO, so use the COCO-trained model to test is tricky.

**Comment by zeruniverse** [comment]
Note: All models are trained on coco first then fine tuned

**Comment by GlebSBrykin** [comment]
I must say that the new version of the neural network is better at dealing only with objects, and with images of places - no. I think it makes sense to train the network on ImageNet or a mixture of COCO and Places.

**Comment by zeruniverse** [comment]
@PABCSoft  I updated with new models finetuned in Places 2.

Please use 
[weight.json.zip](https://github.com/zeruniverse/neural-colorization/files/2220582/weight.json.zip)

Also, compare your result (for the above weights) with mine here: https://github.com/zeruniverse/neural-colorization/releases/download/1.1/sample_images.zip

**Comment by bolimath** [comment]
Thanks! I will try the new model.

**Comment by zeruniverse** [comment]
@bolimath for pytorch .pth weights, it's already updated in release, you don't need `weight.json.zip`. This file is for PABCSoft working with Pascal

**Comment by bolimath** [comment]
Ok, I got it. Thank you!

**Comment by GlebSBrykin** [comment]
Hello! I have tested the new model and am very happy with it! It works fine, but I have one question: what size images were used in training? My implementation scales the input images to a fixed size, allowing you to choose the best quality.

**Comment by zeruniverse** [comment]
Training size is 256*256

**Comment by GlebSBrykin** [comment]
Good. But contrary to common sense, the size of 640x480 was optimal. You can try my new version(C# implementation).
[EN.zip](https://github.com/zeruniverse/neural-colorization/files/2224836/EN.zip)

**Comment by zeruniverse** [comment]
For FCN, the training size doesn’t matter much. I would expect better
quality if inference on HD image as well

**Comment by GlebSBrykin** [comment]
That's what I'm saying. My program scales the input image to a fixed size (now 640x480), then runs it through the neural network, scaling the result to the input size. It works better than 256x256.

**Comment by GlebSBrykin** [comment]
And if you teach a neural network on ImageNet?

**Comment by zeruniverse** [comment]
No. Places2

**Comment by zeruniverse** [comment]
@PABCSoft Could you update the weights? I will add a link in my project to yours after you do it.

**Comment by GlebSBrykin** [comment]
Sorry for the delay, I was very busy. The repository is fully updated. Here is a branch for the English version on PascalABC.NET: https://github.com/PABCSoft/FastNeuralColor/tree/PABC_En

**Comment by CureMe0206** [comment]
Hello, may I ask why I can't download the D.pth file, it shows no resources. Can you pass the file to my mailbox?
my mail box:1149888235@qq.com
thank！

**Comment by zeruniverse** [comment]
@CureMe0206 Sorry I didn't see your comment. GitHub release uses Amazon S3, which is known to have issues due to GFW in China. The file is pretty big and I don't think it's possible for it to be sent as an attachment. Please use some good VPN (like ExpressVPN) or self hosted shadowsocks to download the file again.
