### ISSUE TITLE
Implement pytorch version and GAN

### ISSUE THREAD

**Issue by zeruniverse** [zeruniverse/neural-colorization#4]
Use GAN to remove gray artifacts

Translate to pytorch WIP:
[pytorch.zip](https://github.com/zeruniverse/neural-colorization/files/2173237/pytorch.zip)

**Comment by zeruniverse** [comment]
[model.zip](https://github.com/zeruniverse/neural-colorization/files/2173238/model.zip)

**Comment by GlebSBrykin** [comment]
Does this model use GAN?

**Comment by zeruniverse** [comment]
Currently no. But even with GAN the inference model should be the same. The
difference is only in training

**Comment by GlebSBrykin** [comment]
I hope that GAN will appear soon.

**Comment by zeruniverse** [comment]
[GAN.ipynb.zip](https://github.com/zeruniverse/neural-colorization/files/2182770/GAN.ipynb.zip)

**Comment by GlebSBrykin** [comment]
Will the weights be in JSON?

**Comment by zeruniverse** [comment]
Done

**Comment by bolimath** [comment]
Hi,
which dataset is used for training the model provided on the GitHub page. h <https://github.com/zeruniverse/neural-colorization/releases/download/1.1/G.pth>ttps://github.com/zeruniverse/neural-colorization/releases/download/1.1/G.pth <https://github.com/zeruniverse/neural-colorization/releases/download/1.1/G.pth>
