### ISSUE TITLE
Self Training Throw error, mis matching in shape

### ISSUE THREAD

**Issue by liangmuxin** [zeruniverse/neural-colorization#6]
Hi, I am using this repo to train a image colorization model for a project. And I tried to use train.py to do some training using pretrained model D and G. The errors come out as:
`-> g_loss_gan = adversarial_loss(D(gen_imgs), valid)
(Pdb) 
RuntimeError: size mismatch, m1: [20 x 512], m2: [2048 x 1] at /opt/conda/conda-bld/pytorch_1535491974311/work/aten/src/THC/generic/THCTensor
MathBlas.cu:249`
Where
`(Pdb) type(D)
<class 'torchvision.models.resnet.ResNet'>`
and 
`(Pdb) gen_imgs.shape
torch.Size([20, 3, 256, 256])`
The images are shaped into 256*256 
Is anything incorrect here?

**Comment by zeruniverse** [comment]
Can you provide the version of pytorch and python you are using? I think maybe the model ResNet changed a bit since my last run…

**Comment by liangmuxin** [comment]
![image](https://user-images.githubusercontent.com/11765326/56467622-2071f080-63d6-11e9-95ef-0f014f57bbb4.png)

**Comment by zeruniverse** [comment]
Umm seems like the same issue with #5 

I just trained my self 10 seconds ago with fresh installed anaconda. There's no problem...

```bash
$ wget https://github.com/zeruniverse/neural-colorization/releases/download/1.1/D.pth
$ wget https://github.com/zeruniverse/neural-colorization/releases/download/1.1/G.pth
$ python train.py -d ~/e -c ckp --d_init D.pth --g_init G.pth
Epoch: 0: [D loss: 2.127086] [G total loss: 10.584246] [G GAN Loss: 0.015910]
Epoch: 0: [D loss: 0.047321] [G total loss: 34.186852] [G GAN Loss: 10.139674]
```
My anaconda has python 3.6.8 and pytorch 1.0. But 0.4 should work since this project hasn't been touched since 0.3...

My `gen_imgs` has shape `torch.Size([20, 3, 256, 256])`, both `valid` and `D(gen_imgs)` have `torch.Size([20, 1])`

First step to debug, do the following.

After [Line 93](https://github.com/zeruniverse/neural-colorization/blob/pytorch/train.py#L93), insert a new line:
```python
print(yuv.shape)
```
if this is not always `(256, 256, 3)`, you should change [LN92](https://github.com/zeruniverse/neural-colorization/blob/pytorch/train.py#L92) from `img = Image.open(self.files[index])` to `img = Image.open(self.files[index]).convert('RGB').resize((256,256))`

If above doesn't work,

```bash
pip install torchsummary
```

and in `train.py`, `from torchsummary import summary`, before `for epoch in range(args.epoch):`, insert this line `summary(D,input_size=(3,256, 256))`, compare your output with mine (mine works perfectly)

```
----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
================================================================
            Conv2d-1         [-1, 64, 128, 128]           9,408
       BatchNorm2d-2         [-1, 64, 128, 128]             128
              ReLU-3         [-1, 64, 128, 128]               0
         MaxPool2d-4           [-1, 64, 64, 64]               0
            Conv2d-5           [-1, 64, 64, 64]          36,864
       BatchNorm2d-6           [-1, 64, 64, 64]             128
              ReLU-7           [-1, 64, 64, 64]               0
            Conv2d-8           [-1, 64, 64, 64]          36,864
       BatchNorm2d-9           [-1, 64, 64, 64]             128
             ReLU-10           [-1, 64, 64, 64]               0
       BasicBlock-11           [-1, 64, 64, 64]               0
           Conv2d-12           [-1, 64, 64, 64]          36,864
      BatchNorm2d-13           [-1, 64, 64, 64]             128
             ReLU-14           [-1, 64, 64, 64]               0
           Conv2d-15           [-1, 64, 64, 64]          36,864
      BatchNorm2d-16           [-1, 64, 64, 64]             128
             ReLU-17           [-1, 64, 64, 64]               0
       BasicBlock-18           [-1, 64, 64, 64]               0
           Conv2d-19          [-1, 128, 32, 32]          73,728
      BatchNorm2d-20          [-1, 128, 32, 32]             256
             ReLU-21          [-1, 128, 32, 32]               0
           Conv2d-22          [-1, 128, 32, 32]         147,456
      BatchNorm2d-23          [-1, 128, 32, 32]             256
           Conv2d-24          [-1, 128, 32, 32]           8,192
      BatchNorm2d-25          [-1, 128, 32, 32]             256
             ReLU-26          [-1, 128, 32, 32]               0
       BasicBlock-27          [-1, 128, 32, 32]               0
           Conv2d-28          [-1, 128, 32, 32]         147,456
      BatchNorm2d-29          [-1, 128, 32, 32]             256
             ReLU-30          [-1, 128, 32, 32]               0
           Conv2d-31          [-1, 128, 32, 32]         147,456
      BatchNorm2d-32          [-1, 128, 32, 32]             256
             ReLU-33          [-1, 128, 32, 32]               0
       BasicBlock-34          [-1, 128, 32, 32]               0
           Conv2d-35          [-1, 256, 16, 16]         294,912
      BatchNorm2d-36          [-1, 256, 16, 16]             512
             ReLU-37          [-1, 256, 16, 16]               0
           Conv2d-38          [-1, 256, 16, 16]         589,824
      BatchNorm2d-39          [-1, 256, 16, 16]             512
           Conv2d-40          [-1, 256, 16, 16]          32,768
      BatchNorm2d-41          [-1, 256, 16, 16]             512
             ReLU-42          [-1, 256, 16, 16]               0
       BasicBlock-43          [-1, 256, 16, 16]               0
           Conv2d-44          [-1, 256, 16, 16]         589,824
      BatchNorm2d-45          [-1, 256, 16, 16]             512
             ReLU-46          [-1, 256, 16, 16]               0
           Conv2d-47          [-1, 256, 16, 16]         589,824
      BatchNorm2d-48          [-1, 256, 16, 16]             512
             ReLU-49          [-1, 256, 16, 16]               0
       BasicBlock-50          [-1, 256, 16, 16]               0
           Conv2d-51            [-1, 512, 8, 8]       1,179,648
      BatchNorm2d-52            [-1, 512, 8, 8]           1,024
             ReLU-53            [-1, 512, 8, 8]               0
           Conv2d-54            [-1, 512, 8, 8]       2,359,296
      BatchNorm2d-55            [-1, 512, 8, 8]           1,024
           Conv2d-56            [-1, 512, 8, 8]         131,072
      BatchNorm2d-57            [-1, 512, 8, 8]           1,024
             ReLU-58            [-1, 512, 8, 8]               0
       BasicBlock-59            [-1, 512, 8, 8]               0
           Conv2d-60            [-1, 512, 8, 8]       2,359,296
      BatchNorm2d-61            [-1, 512, 8, 8]           1,024
             ReLU-62            [-1, 512, 8, 8]               0
           Conv2d-63            [-1, 512, 8, 8]       2,359,296
      BatchNorm2d-64            [-1, 512, 8, 8]           1,024
             ReLU-65            [-1, 512, 8, 8]               0
       BasicBlock-66            [-1, 512, 8, 8]               0
        AvgPool2d-67            [-1, 512, 2, 2]               0
           Linear-68                    [-1, 1]           2,049
          Sigmoid-69                    [-1, 1]               0
================================================================
Total params: 11,178,561
Trainable params: 11,178,561
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 0.75
Forward/backward pass size (MB): 82.02
Params size (MB): 42.64
Estimated Total Size (MB): 125.41
----------------------------------------------------------------
```
Let me know if the above helps.

**Comment by zeruniverse** [comment]
Any updates @liangmuxin ?

**Comment by liangmuxin** [comment]
i was busy with other part of project recently. I will try it in weekend.

Jeffery Zhao <notifications@github.com>于2019年4月23日 周二下午8:30写道：

**Comment by liangmuxin** [comment]
thanks for the detailed instruction! I will definitely give update after
trying

Muxin Liang <muxinlia@usc.edu>于2019年4月23日 周二下午8:31写道：

**Comment by liangmuxin** [comment]
Well... None of the methods work.
summary refused to give results:

> RuntimeError: size mismatch, m1: [2 x 512], m2: [2048 x 1] at /opt/conda/conda-bld/pytorch_1535491974311/work/aten/src/THC/generic/THCTensorMathBlas.cu:249
> /home/hyper950412/neural-colorization/train.py(147)<module>()
-> summary(D,input_size=(3,256, 256))

**Comment by zeruniverse** [comment]
What if you try summary(D,input_size=(256,256,3))?

**Comment by liangmuxin** [comment]
> RuntimeError: Given groups=1, weight of size [64, 3, 7, 7], expected input[2, 256, 256, 3] to have 3 channels, but got 256 channels instead
> /home/hyper950412/neural-colorization/train.py(147)<module>()
-> summary(D,input_size=(256, 256, 3))
(Pdb)

**Comment by zeruniverse** [comment]
I can’t reproduce your bug. If you can give me ssh to your machine, I might
be able to debug for you. You can send it to zzy8200#gmail.com

**Comment by zeruniverse** [comment]
And can you try to upgrade your torchvision and pytorch package to the
latest? I used a docker with everything newly installed. The training runs
without any problem out of the box

**Comment by liangmuxin** [comment]
I updated both, still not working

**Comment by zeruniverse** [comment]
If you can give me ssh to your machine, I can help you debug. Otherwise you
might have to debug yourself since I can’t reproduce the bug you had.
Sorry...

**Comment by bolimath** [comment]
@zeruniverse  How long will it cost for training on ImageNet ILSVRC12 on a single GPU? My GPU is TITAN Xp with 12G memory.

**Comment by zeruniverse** [comment]
@bolimath I never trained with imagenet. I only trained with places365. This is an old project so I can't remember the exact time... If you'd like to do me a favor, you can report the training statistics so I'll put them on README. By the way, did you encounter the issue @liangmuxin reported? I personally don't have any issue running the scripts.

**Comment by Leo-xh** [comment]
I think the problems result from the version of torchvision, which version of torchvision do you use?

**Comment by xihuai18** [comment]
I fixed that. The problem is in line 109, it should be changed to D.fc = nn.Sequential(nn.Linear(512, 1), nn.Sigmoid()), referring to the picture below.
![image](https://user-images.githubusercontent.com/23721828/57579887-59811a80-74d5-11e9-8d1d-3f898106268d.png)

**Comment by zeruniverse** [comment]
Umm, that will make the pretrained weights invalid. But thanks for pointing
it out. I’ll give it a closer look next week. It’s actually pretty
surprising that torchvision changed network architecture for ResNet-18
among versions.

**Comment by xihuai18** [comment]
Yes, thank you for providing such a project, I can train the fc of the discriminator from scratch.

**Comment by zeruniverse** [comment]
@Leo-xh I confirmed this problem. If it's possible, could you provide a pre-trained model? The old model will not work anymore due to the arch change in `D`

**Comment by zeruniverse** [comment]
For some reasons I didn't get the newest `torchvision` when I do `pip install` at the beginning of this issue. My apologise.

**Comment by xihuai18** [comment]
It is embarrassing that I trained my network to segment people's hands. My model is not suited for general use.

**Comment by zeruniverse** [comment]
OK. then I'll retrain it when i have time
